export const InstructorEvents = {
  PRACTICE_COMPLETED: "PRACTICE_COMPLETED",
  JUSTIFICATION_VIEWED: "JUSTIFICATION_VIEWED",
  ABOUT_OPENED: "ABOUT_OPENED",
  ADVANCED_MODE_STARTED: "ADVANCED_MODE_STARTED",
};
